export const rowData = [
  {
    id: 4,
    number: 12456,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 4,
    participants: ['Participant 1', 'Participant 2', 'Participant 3'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 5,
    number: 12457,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 1,
    participants: ['Participant 1', 'Participant 2', 'Participant 3'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 6,
    number: 12458,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 4,
    participants: ['Participant 1', 'Participant 2', 'Participant 3'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 7,
    number: 12459,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2', 'Participant 3'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 8,
    number: 12460,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2', 'Participant 3'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 9,
    number: 12461,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2', 'Participant 3'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 10,
    number: 12498,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 11,
    number: 12488,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 12,
    number: 12489,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 5,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 13,
    number: 12490,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 14,
    number: 12491,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 15,
    number: 12492,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 16,
    number: 12493,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 17,
    number: 12494,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 0,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 18,
    number: 12495,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 2,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-09',
    last_modified: '2022-12-24',
    approved_at: ''
  },
  {
    id: 19,
    number: 12496,
    class: 'A',
    lot_species: 'SX - Spruce hibrid',
    form_step: 'Collection',
    status: 3,
    participants: ['Participant 1', 'Participant 2'],
    created_at: '2021-10-10',
    last_modified: '2022-12-23',
    approved_at: ''
  },
];
export const headerData = [
  {
    key: 'number',
    header: 'Seedlot number',
  },
  {
    key: 'class',
    header: 'Lot class',
  },
  {
    key: 'lot_species',
    header: 'Lot species',
  },
  {
    key: 'form_step',
    header: 'Form step',
  },
  {
    key: 'status',
    header: 'Status',
  },
  {
    key: 'participants',
    header: 'Participants',
  },
  {
    key: 'created_at',
    header: 'Created at',
  },
  {
    key: 'last_modified',
    header: 'Last modified',
  },
  {
    key: 'approved_at',
    header: 'Approved at',
  },
];
